name: iiProductions
favicon: null
layout_spectrum: 0.5297786972951144
typography_spectrum: 0.8712890925817192
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2674470110796392
  lightness: 0.1972594573162496
  saturation: 0.4976831544190645
  rhythmicContrast: 0.23664814652875066
purpose: []
