name: iiProductions
favicon: null
layout_spectrum: 0.23295
typography_spectrum: 0.56241
title: Untitled
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.125
  lightness: 0.9375
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
