name: Untitled
favicon: null
layout_spectrum: 0
typography_spectrum: 0.62161
title: Untitled
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbd350'
    - '#fdc828'
    - '#f1c001'
    - '#fbc472'
    - '#faba24'
  brandStrength: 0.125
  lightness: 0
  saturation: 0.875
  rhythmicContrast: 1
purpose: []
